fixing undefined reference to g_bus_get_sync in Bluetooth Plugin
WPEFramework fails to start when Bluetooth plugin is enabled because of
the undefined reference to libgio function (ie g_bus_get_sync). This
will link libgio-2.0 to the Bluetooth plugin.